### ISSUE TITLE
Hardcoded path for wala.properties

### ISSUE THREAD

**Issue by jcp19** [MagpieBridge/IRConverter#2]
Hey there,
I believe that it would be better to allow the user to specify the path for the **wala.properties** file instead of having it hardcoded in the **WalaToSootIRConverter** like this:
https://github.com/MagpieBridge/IRConverter/blob/1bdba85718ac17f7fbb26b89bc4dcaba499fa744/src/main/java/magpiebridge/converter/WalaToSootIRConverter.java#L42

This bit me once when I was trying to run a Soot based analysis on a MagpieServer connected to Eclipse on Windows. It crashed with a `FileNotFoundException` in line
https://github.com/MagpieBridge/IRConverter/blob/1bdba85718ac17f7fbb26b89bc4dcaba499fa744/src/main/java/magpiebridge/converter/WalaToSootIRConverter.java#L161
because it was trying to create that file in **C:\Windows\System32**. If you run eclipse as administrator once, it will create the file and the error will go away but still, it would be useful to be able to chose another path 😄

**Comment by linghuiluo** [comment]
@jcp19 Hi, yeah. This is a good point. I will add an option for this. :)

**Comment by linghuiluo** [comment]
@jcp19 I made a new release 0.1.4. please see if this is what you want:

https://github.com/MagpieBridge/IRConverter/blob/783b5772e3ea61e76c9cd92b502543fe250acd8e/src/test/java/magpiebridge/converter/integration/WalaOptionsTest.java#L23-L46

**Comment by jcp19** [comment]
Yes, that's definitely better! Thank you for your fast reply 😊
